### ISSUE TITLE
Floating, Immortal Ghost Pigs

### ISSUE THREAD

**Issue by cannotbeme** [bl4ckscor3/Sit#15]
If you shift + rightclick on a slab that is the lower part of a block, the pig you are supposed to sit on appears, but you don't sit on it, which results in you summoning Pigs, that cannot be killed, can't move and float.
![2021-02-13_13 03 04](https://user-images.githubusercontent.com/78547213/107849745-a2c67280-6dfd-11eb-9c84-b08d30750848.png)
![2021-02-13_13 06 00](https://user-images.githubusercontent.com/78547213/107849769-c5588b80-6dfd-11eb-8114-d5dd32337fa6.png)

**Comment by bl4ckscor3** [comment]
This mod does not work by sitting on pigs. You must be using a different mod/plugin that adds sitting functionality.

EDIT 7. April 2021: I've now learned that this is, in fact, caused by the Fabric version of Sit only being present on the server. **You have to install the mod on both client _and_ server for it to work properly.**
I was under the impression that Fabric, just like Forge, rejects client connections if the client does not have the same registry data (blocks/items/entities/...) present as the server. This is not true. The fact that Fabric allows clients with missing data to connect is what causes this issue. Fabric seems to be using Pigs as a placeholder for missing entities (I could be wrong with that, but that's what it looks like).
