### ISSUE TITLE
Server hosted behind a proxy kicks players on joining.

### ISSUE THREAD

**Issue by di3d** [bl4ckscor3/Sit#18]
As described above, this occurs. Both client and server have the correct version of this mod.
Is it possible to disable this check through a config option or something as such?

![image](https://user-images.githubusercontent.com/26273961/148641458-9372ce95-e4b4-4224-9cc6-cae200929c15.png)

**Comment by bl4ckscor3** [comment]
Added a config option in version 16 to disable that check: https://www.curseforge.com/minecraft/mc-mods/sit-fabric/files/3598393

**Comment by weh** [comment]
just ran into the exact same issue.
- server: sit-1.18.2-19.jar
- client: sit-1.18.2-19.jar

I checked on the client, that the mod is really loaded, and it was.

On server connect, the connection was denied because of this mod. Solved it by disabling the check. But maybe you should fix the check, or disable it by default?
