### ISSUE TITLE
Modded Blocks

### ISSUE THREAD

**Issue by maxanier** [bl4ckscor3/Sit#19]
Hello,

I am the (co-)author of [Vampirism](https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire) mod.
For a new block (a throne) I would like to implement a sit functionality similar to how your mod allows sitting on slabs.
I noticed that your have/had support for slabs from Immersive Engineering slabs. So I was wondering if you are interested in adding support for other blocks as well. I have also seen #8, which would work as well. I would assume there are other mods that could be interested in such feature.
If you are not interested in this, I would like to copy/modify your code to our own code. Our mod is LGPLv3 not GPL3, but I would move things to a separate package and add a clear License header, if you agree. 
Of course I could also write an entirely new system, but why reinvent the wheel. Also my solution would likely look similar to yours as it is a rather simple function with clear requirements.

**Comment by bl4ckscor3** [comment]
Since Sit is for sitting on slabs and stairs, I will not add support for other blocks that are not slabs or stairs (no matter if modded or not). I think it's better to have this built into your mod anyways, since forcing players to install mod B they potentially don't want to enable a feature in mod A isn't great. Thus I'm happily giving you permission to use this mod's code for your purpose.

A sidenote: As long as modded slabs/stairs extend the vanilla slab/stair block classes, they will automatically be supported. I had to add support for Immersive Engineering's slabs in 1.12, because they did not do so.

**Comment by maxanier** [comment]
yes, having it directly in the mod is of course better. But I thought making sitting optionally and dependent on Sit would be acceptable for players.

Anyways, then I will add it directly. Thank you for clarifying the scope of this mod and granting permission   :)
