### ISSUE TITLE
Items held in the offhand still work when sitting down

### ISSUE THREAD

**Issue by Dejeh** [bl4ckscor3/Sit#20]
When using the wrench from Additionally Additions on a stair/slab it can be a bit buggy. It'd be nice if we could disable the sit feature when holding it

**Comment by bl4ckscor3** [comment]
I've made it so you're only able to sit when your main hand is empty because of this. However when holding such an item in the offhand, it still works even when the player is sitting down. I agree this is not great behavior, however I tried out something that should deal with this (for those interested `event.setUseItem(Result.DENY);`) but it doesn't seem to stop offhand items from doing what they are doing, even though it should work. This could be a Forge bug but I am uncertain.
