### ISSUE TITLE
Getting up from slabs with nothing under it causes the player to fall through the floor

### ISSUE THREAD

**Issue by Ayutac** [bl4ckscor3/Sit#22]
On MC 1.18.2 I have a floor made out of slabs and when I sit on the floor and get up, I fall through it.

Possibly a duplicate of #2, but the kind of solution (invalid, etc) isn't tagged there, so to be sure I open a new ticket.

**Comment by bl4ckscor3** [comment]
That issue was closed because I couldn't decipher what the person meant and wanted to get clarification from them, which never happened. As for this specific issue, it'll be fixed in the next version of the mod that I will release today.

**Comment by FunElectric** [comment]
Hello! I'm a different person experiencing the same issue in 1.12.2 [sit-1.12.2-v1.3.jar].

This bug (at least for me) seems to occur on a mod called Mo' Bends (also tested on a super-flat world with these 2 mods exclusively). Could this be an overall incompatibility for custom animation mods?
Since Mo' Bends is allegedly a client-side mod [according to https://www.curseforge.com/minecraft/mc-mods/mo-bends], this bug might cause some odd exploits, especially in Multiplayer, if someone were to have Mo' Bends installed while the rest don't.

Here is an example of the bug occurring on a modded Minecraft world:

> Standing still:
![2022-07-23_17 26 34](https://user-images.githubusercontent.com/87086653/180610374-5c8122ed-6035-41d1-9565-7b6fb3244283.png)

> After unmounting the slab:
![2022-07-23_17 26 37](https://user-images.githubusercontent.com/87086653/180610378-e73f5967-693e-4786-ac03-c3df73bc3930.png)

Should I make this an issue of its own?
